version: "3"
services:
  client:
    container_name: client
    image: client
    build: ./client
    ports:
      - "3000:3000"
  server:
    container_name: server
    image: server
    build: .
    ports: 
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/sachhay
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo
    image: "mongo"
    ports: 
      - "27017:27017"
