export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST"
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS"
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE"

export const FETCH_BOOK_REQUEST = "FETCH_BOOK_REQUEST"
export const FETCH_BOOK_SUCCESS = "FETCH_BOOK_SUCCESS"
export const FETCH_BOOK_FAILURE = "FETCH_BOOK_FAILURE"

export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST"
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS"
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE"

export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST"
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS"
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE"

export const SEARCH_BOOKS_REQUEST = "SEARCH_BOOKS_REQUEST"
export const SEARCH_BOOKS_SUCCESS="SEARCH_BOOKS_SUCCESS"
export const SEARCH_BOOKS_FAILURE="SEARCH_BOOKS_FAILURE"
